version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            ./install.sh
      - run:
          name: run
          command: |
            python runner.py